global.armourList = json_decode(@'
{
	"A000": {
		"name": "Black Jacket",
		"damageBonus": 0,
		"bonusStress": 0,
		"bonusVul": -1,
		"bonusHP": 0,
		"bonusMag": 0,
		"bonusPow": 0,
		"bonusVel": 0,
		"bonusVig": 0,
		"bonusPer": 0,
		"bonusLog": 0,
		"status0": "noone",
		"status1": "noone",
		"status2": "noone",
		"spell": "noone",
		"desc":"Black Jacket: Armour | Vul:-1 "
	},
	"A001": {
		"name": "Flaming T-shirt",
		"damageBonus": 0,
		"bonusStress": 0,
		"bonusVul": -1,
		"bonusHP": 2,
		"bonusMag": 0,
		"bonusPow": 0,
		"bonusVel": 0,
		"bonusVig": 0,
		"bonusPer": 0,
		"bonusLog": 0,
		"status0": "noone",
		"status1": "noone",
		"status2": "noone",
		"spell": "noone",
		"desc":"Flaming T-shirt: Armour | Vul:-1 | HP+2 "
	},
	"A002": {
		"name": "White Coat",
		"damageBonus": 0,
		"bonusStress": 0,
		"bonusVul": -2,
		"bonusHP": 0,
		"bonusMag": 0,
		"bonusPow": 0,
		"bonusVel": 0,
		"bonusVig": 0,
		"bonusPer": 0,
		"bonusLog": 0,
		"status0": "noone",
		"status1": "noone",
		"status2": "noone",
		"spell": "noone",
		"desc":"White Coat: Armour | Vul:-2 "
	},
	"A003": {
		"name": "Water Skin",
		"damageBonus": 0,
		"bonusStress": 0,
		"bonusVul": -2,
		"bonusHP": 0,
		"bonusMag": 0,
		"bonusPow": 0,
		"bonusVel": 4,
		"bonusVig": 0,
		"bonusPer": 0,
		"bonusLog": 0,
		"status0": "noone",
		"status1": "noone",
		"status2": "noone",
		"spell": "noone",
		"desc":"Water Skin: Armour | Vul:-2 | VEL:+1 "
	}
}
')