global.weaponList = json_decode(@'
{
	"W000": {
		"name": "Iron Knife",
		"damage": "dice_1d4",
		"2hands": false,
		"damageType": "S",
		"attacks": ["Precise Attack", "Powerfull Attack"],
		"damageBonus": 0,
		"bonusStress": 0,
		"bonusVul": 0,
		"bonusHP": 0,
		"bonusMag": 0,
		"bonusPow": 0,
		"bonusVel": 0,
		"bonusVig": 0,
		"bonusPer": 0,
		"bonusLog": 0,
		"status0": "noone",
		"status1": "noone",
		"status2": "noone",
		"spell": "noone",
		"desc":"Iron Knife: Weapon | DMG:1d4 | Type :S"
	},
	"W001": {
		"name": "Baseball Bat",
		"damage": "dice_1d6",
		"2hands": true,
		"damageType": "B",
		"attacks": ["Precise Attack", "Powerfull Attack"],
		"damageBonus": -1,
		"bonusStress": 0,
		"bonusVul": 0,
		"bonusHP": 0,
		"bonusMag": 0,
		"bonusPow": 0,
		"bonusVel": 0,
		"bonusVig": 0,
		"bonusPer": 0,
		"bonusLog": 0,
		"status0": "noone",
		"status1": "noone",
		"status2": "noone",
		"spell": "noone",
		"desc":"Baseball Bat: Weapon | DMG:1d6-1 | Type :B"
	},
	"W002": {
		"name": "Wooding Axe",
		"damage": "dice_1d6",
		"2hands": true,
		"damageType": "B",
		"attacks": ["Precise Attack", "Powerfull Attack"],
		"damageBonus": 1,
		"bonusStress": 0,
		"bonusVul": 0,
		"bonusHP": 0,
		"bonusMag": 0,
		"bonusPow": 0,
		"bonusVel": 0,
		"bonusVig": 0,
		"bonusPer": 0,
		"bonusLog": 0,
		"status0": "noone",
		"status1": "noone",
		"status2": "noone",
		"spell": "noone",
		"desc":"Wooding Axe: Weapon | DMG:1d9+1 | Type :B"
	}
}
')